In [1]:
import json
import os

from matplotlib import pyplot as plt
import torch

In [3]:
!python3 data.py

In [4]:
!python3 fcann2.py

iteration 0: loss 6.213158795908594
iteration 1000: loss 0.43680931078742025
iteration 2000: loss 0.3627567122962079
iteration 3000: loss 0.3219699080022129
iteration 4000: loss 0.30594145811860385


In [5]:
!python3 pt_linreg.py

step: 0, loss:8.269914627075195, Y_:tensor([0.7923, 1.5844], grad_fn=<AddBackward0>)
a:tensor([1.6960], requires_grad=True), a_grad:tensor([-9.0388]), a_grad_manual: -9.0388
 b:tensor([0.5626], requires_grad=True), b_grad:tensor([-5.6232]), b_grad_manual: -5.6232
step: 1, loss:0.8213987350463867, Y_:tensor([2.2585, 3.9545], grad_fn=<AddBackward0>)
a:tensor([1.9792], requires_grad=True), a_grad:tensor([-2.8324]), a_grad_manual: -2.8324
 b:tensor([0.7413], requires_grad=True), b_grad:tensor([-1.7869]), b_grad_manual: -1.7869
step: 2, loss:0.08415773510932922, Y_:tensor([2.7205, 4.6997], grad_fn=<AddBackward0>)
a:tensor([2.0672], requires_grad=True), a_grad:tensor([-0.8801]), a_grad_manual: -0.8801
 b:tensor([0.7992], requires_grad=True), b_grad:tensor([-0.5798]), b_grad_manual: -0.5798
step: 3, loss:0.011112354695796967, Y_:tensor([2.8665, 4.9337], grad_fn=<AddBackward0>)
a:tensor([2.0938], requires_grad=True), a_grad:tensor([-0.2661]), a_grad_manual: -0.2661
 b:tensor([0.8192], requires

In [7]:
!python3 pt_logreg.py

iteration 0: loss 1.677825692339311
iteration 1000: loss 0.08812137120208574
iteration 2000: loss 0.08132796013957298
iteration 3000: loss 0.07779480319506155
iteration 4000: loss 0.07550351835010251
iteration 5000: loss 0.07382796197697139
iteration 6000: loss 0.07251144907986762
[(0.97, 0.9603960396039604), (0.96, 0.9795918367346939), (1.0, 0.9900990099009901)] [[ 97   2   1]
 [  4  96   0]
 [  0   0 100]]



In [8]:
!python3 pt_deep.py # data 4,2,40 i nn 2,2

iteration 0: loss 0.7085322737693787
iteration 1000: loss 0.5561569929122925
iteration 2000: loss 0.5397718548774719
iteration 3000: loss 0.516151487827301
iteration 4000: loss 0.5093638300895691
iteration 5000: loss 0.5050562620162964
iteration 6000: loss 0.5005543828010559
iteration 7000: loss 0.4954639971256256
iteration 8000: loss 0.4938802719116211
iteration 9000: loss 0.49276405572891235
iteration 10000: loss 0.4918145537376404
recall:[(0.8875, 0.7634408602150538), (0.725, 0.8656716417910447)]
precision: [[71  9]
 [22 58]]
accuracy: 0.80625


In [9]:
!python3 pt_deep.py # data 4,2,40 i nn 2,10,2

iteration 0: loss 1.8447242975234985
iteration 1000: loss 0.44838887453079224
iteration 2000: loss 0.44191694259643555
iteration 3000: loss 0.439502090215683
iteration 4000: loss 0.4377194941043854
iteration 5000: loss 0.4360786974430084
iteration 6000: loss 0.4348193109035492
iteration 7000: loss 0.4338065981864929
iteration 8000: loss 0.43284493684768677
iteration 9000: loss 0.4319119453430176
iteration 10000: loss 0.4311864972114563
recall:[(0.975, 0.8387096774193549), (0.8125, 0.9701492537313433)]
precision: [[78  2]
 [15 65]]
accuracy: 0.89375


In [14]:
!python3 pt_deep.py # data 4,2,40 i nn 2,10,10,2

iteration 0: loss 9.569859504699707
iteration 1000: loss 0.2695121169090271
iteration 2000: loss 0.23024551570415497
iteration 3000: loss 0.2169807404279709
iteration 4000: loss 0.20975545048713684
iteration 5000: loss 0.20625510811805725
iteration 6000: loss 0.1577834188938141
iteration 7000: loss 0.151149719953537
iteration 8000: loss 0.1482793241739273
iteration 9000: loss 0.14646214246749878
iteration 10000: loss 0.14487071335315704
recall:[(0.9625, 0.9390243902439024), (0.9375, 0.9615384615384616)]
precision: [[77  3]
 [ 5 75]]
accuracy: 0.95


In [11]:
!python3 pt_deep.py # data 6,2,10 i nn 2,2

iteration 0: loss 1.458279013633728
iteration 1000: loss 0.5678195357322693
iteration 2000: loss 0.5414180755615234
iteration 3000: loss 0.530247151851654
iteration 4000: loss 0.5240134000778198
iteration 5000: loss 0.5196540355682373
iteration 6000: loss 0.5149585008621216
iteration 7000: loss 0.5115464329719543
iteration 8000: loss 0.5087001323699951
iteration 9000: loss 0.5063870549201965
iteration 10000: loss 0.5048836469650269
recall:[(0.9333333333333333, 0.6363636363636364), (0.4666666666666667, 0.875)]
precision: [[28  2]
 [16 14]]
accuracy: 0.7


In [12]:
!python3 pt_deep.py # data 6,2,10 i nn 2,10,2

iteration 0: loss 8.707029342651367
iteration 1000: loss 0.5777360796928406
iteration 2000: loss 0.5521997809410095
iteration 3000: loss 0.5005514025688171
iteration 4000: loss 0.4959138035774231
iteration 5000: loss 0.4900909662246704
iteration 6000: loss 0.48911893367767334
iteration 7000: loss 0.4882875680923462
iteration 8000: loss 0.48812976479530334
iteration 9000: loss 0.48811835050582886
iteration 10000: loss 0.48760560154914856
recall:[(1.0, 0.6), (0.3333333333333333, 1.0)]
precision: [[30  0]
 [20 10]]
accuracy: 0.6666666666666666


In [23]:
!python3 ksvm_wrap.py

recall:[(1.0, 0.8823529411764706), (0.8666666666666667, 1.0)]
precision: [[30  0]
 [ 4 26]]
accuracy: 0.9333333333333333


In [25]:
!python3 mnist_shootout.py

cpu
60000 784 10
torch.Size([60000, 28, 28])
torch.Size([10000, 28, 28])
iteration 0: loss 7.5960373878479
iteration 1000: loss 1.8547776937484741
iteration 2000: loss 1.6549408435821533
iteration 3000: loss 1.5554481744766235
iteration 4000: loss 1.471063494682312
[(0.9693877551020408, 0.1754710011082379), (0.9154185022026432, 0.9066317626527051), (0.001937984496124031, 0.3333333333333333), (0.804950495049505, 0.8017751479289941), (0.8289205702647657, 0.7941463414634147), (0.28699551569506726, 0.6632124352331606), (0.05010438413361169, 0.676056338028169), (0.0, 0.0), (0.002053388090349076, 0.2222222222222222), (0.707631318136769, 0.7710583153347732)]
[[ 950    1    1    2    0   23    2    0    0    1]
 [  87 1039    0    4    2    2    1    0    0    0]
 [ 889   33    2   57   26    5   12    3    1    4]
 [ 161    1    0  813    1   20    2    0    0   12]
 [ 115    3    0    4  814    3    1    0    0   42]
 [ 498   17    2   68   34  256    1    0    2   14]
 [ 844    8    0    2 